export const DEMO_BOOKS = [
  {
    id: 'demo-1',
    userId: 'demo',
    title: 'The Bee Sting',
    author: 'Paul Murray',
    publicationYear: 2023,
    isbn13: null,
    status: 'now_reading',
    category: 'fiction',
    sortOrder: 0,
    description: 'A family novel about the Barnes family and the pressures, secrets, and reversals that gather around them.',
    metadataSource: 'manual',
    metadataSourceId: null,
    bookmarksUrl: null,
    amazonCaUrl: 'https://www.amazon.ca/s?k=The+Bee+Sting+Paul+Murray',
    finishedAt: null,
  },
  {
    id: 'demo-2',
    userId: 'demo',
    title: 'The Dawn of Everything',
    author: 'David Graeber and David Wengrow',
    publicationYear: 2021,
    isbn13: null,
    status: 'now_reading',
    category: 'nonfiction',
    sortOrder: 0,
    description: 'A wide-ranging reconsideration of human prehistory and the conventional stories told about the origins of inequality and social organization.',
    metadataSource: 'manual',
    metadataSourceId: null,
    bookmarksUrl: null,
    amazonCaUrl: 'https://www.amazon.ca/s?k=The+Dawn+of+Everything',
    finishedAt: null,
  },
  {
    id: 'demo-3',
    userId: 'demo',
    title: 'Homeseeking',
    author: 'Karissa Chen',
    publicationYear: 2025,
    isbn13: '9780593712993',
    status: 'queued',
    category: 'fiction',
    sortOrder: 0,
    description: 'A multigenerational story of love, separation, migration, and the search for home.',
    metadataSource: 'manual',
    metadataSourceId: null,
    bookmarksUrl: 'https://bookmarks.reviews/reviews/homeseeking/',
    amazonCaUrl: 'https://www.amazon.ca/s?k=Homeseeking+Karissa+Chen',
    finishedAt: null,
  },
  {
    id: 'demo-4',
    userId: 'demo',
    title: 'The Right Stuff',
    author: 'Tom Wolfe',
    publicationYear: 1979,
    isbn13: null,
    status: 'queued',
    category: 'nonfiction',
    sortOrder: 0,
    description: 'A narrative account of America’s early test pilots and astronauts and the culture that surrounded them.',
    metadataSource: 'manual',
    metadataSourceId: null,
    bookmarksUrl: null,
    amazonCaUrl: 'https://www.amazon.ca/s?k=The+Right+Stuff+Tom+Wolfe',
    finishedAt: null,
  },
];
